apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-rollouts-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: prometheus-rollout-demo.argo.opsmx.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-rollouts-demo
                port:
                  number: 80
