apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-config-new2
data:
  canary.jmx: |
    <?xml version="1.0" encoding="UTF-8"?>
    <jmeterTestPlan version="1.2" properties="5.0" jmeter="5.3">
       <hashTree>
          <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Test Plan" enabled="true">
             <stringProp name="TestPlan.comments" />
             <boolProp name="TestPlan.functional_mode">false</boolProp>
             <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
             <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
             <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
                <collectionProp name="Arguments.arguments" />
             </elementProp>
             <stringProp name="TestPlan.user_define_classpath" />
          </TestPlan>
          <hashTree>
             <Arguments guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
                <collectionProp name="Arguments.arguments">
                   <elementProp name="CANARY_SERVER_IP" elementType="HTTPArgument">
                      <boolProp name="HTTPArgument.always_encode">false</boolProp>
                      <stringProp name="Argument.value">load-svc</stringProp>
                      <stringProp name="Argument.metadata">=</stringProp>
                      <boolProp name="HTTPArgument.use_equals">true</boolProp>
                      <stringProp name="Argument.name">CANARY_SERVER_IP</stringProp>
                   </elementProp>
                   <elementProp name="CANARY_PORT" elementType="HTTPArgument">
                      <boolProp name="HTTPArgument.always_encode">false</boolProp>
                      <stringProp name="Argument.metadata">=</stringProp>
                      <boolProp name="HTTPArgument.use_equals">true</boolProp>
                      <stringProp name="Argument.name">CANARY_PORT</stringProp>
                   </elementProp>
                   <elementProp name="RUN_DURATION" elementType="HTTPArgument">
                      <boolProp name="HTTPArgument.always_encode">false</boolProp>
                      <stringProp name="Argument.value">7200</stringProp>
                      <stringProp name="Argument.metadata">=</stringProp>
                      <boolProp name="HTTPArgument.use_equals">true</boolProp>
                      <stringProp name="Argument.name">RUN_DURATION</stringProp>
                   </elementProp>
                   <elementProp name="REQUESTS" elementType="HTTPArgument">
                      <boolProp name="HTTPArgument.always_encode">false</boolProp>
                      <stringProp name="Argument.value">1000</stringProp>
                      <stringProp name="Argument.metadata">=</stringProp>
                      <boolProp name="HTTPArgument.use_equals">true</boolProp>
                      <stringProp name="Argument.name">REQUESTS</stringProp>
                   </elementProp>
                </collectionProp>
             </Arguments>
             <hashTree />
             <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="CANARY_INFO_THREAD" enabled="true">
                <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
                <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
                   <boolProp name="LoopController.continue_forever">false</boolProp>
                   <intProp name="LoopController.loops">-1</intProp>
                </elementProp>
                <stringProp name="ThreadGroup.num_threads">1</stringProp>
                <stringProp name="ThreadGroup.ramp_time">0</stringProp>
                <boolProp name="ThreadGroup.scheduler">true</boolProp>
                <stringProp name="ThreadGroup.duration">${RUN_DURATION}</stringProp>
                <stringProp name="ThreadGroup.delay" />
                <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
             </ThreadGroup>
             <hashTree>
                <ConstantThroughputTimer guiclass="TestBeanGUI" testclass="ConstantThroughputTimer" testname="Constant Throughput Timer" enabled="true">
                   <intProp name="calcMode">2</intProp>
                   <doubleProp>
                      <name>throughput</name>
                      <value>2000.0</value>
                      <savedValue>0.0</savedValue>
                   </doubleProp>
                </ConstantThroughputTimer>
                <hashTree />
                <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
                   <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
                      <collectionProp name="Arguments.arguments" />
                   </elementProp>
                   <stringProp name="HTTPSampler.domain">${CANARY_SERVER_IP}</stringProp>
                   <stringProp name="HTTPSampler.port">${CANARY_PORT}</stringProp>
                   <stringProp name="HTTPSampler.protocol">http</stringProp>
                   <stringProp name="HTTPSampler.contentEncoding" />
                   <stringProp name="HTTPSampler.path">logs?type=INFO</stringProp>
                   <stringProp name="HTTPSampler.method">GET</stringProp>
                   <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
                   <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
                   <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
                   <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
                   <stringProp name="HTTPSampler.embedded_url_re" />
                   <stringProp name="HTTPSampler.connect_timeout" />
                   <stringProp name="HTTPSampler.response_timeout" />
                </HTTPSamplerProxy>
                <hashTree />
             </hashTree>
             <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="CANARY_DUBUG_THREAD" enabled="true">
                <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
                <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
                   <boolProp name="LoopController.continue_forever">false</boolProp>
                   <intProp name="LoopController.loops">-1</intProp>
                </elementProp>
                <stringProp name="ThreadGroup.num_threads">1</stringProp>
                <stringProp name="ThreadGroup.ramp_time">0</stringProp>
                <boolProp name="ThreadGroup.scheduler">true</boolProp>
                <stringProp name="ThreadGroup.duration">${RUN_DURATION}</stringProp>
                <stringProp name="ThreadGroup.delay" />
                <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
             </ThreadGroup>
             <hashTree>
                <ConstantThroughputTimer guiclass="TestBeanGUI" testclass="ConstantThroughputTimer" testname="Constant Throughput Timer" enabled="true">
                   <intProp name="calcMode">2</intProp>
                   <doubleProp>
                      <name>throughput</name>
                      <value>2000.0</value>
                      <savedValue>0.0</savedValue>
                   </doubleProp>
                </ConstantThroughputTimer>
                <hashTree />
                <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
                   <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
                      <collectionProp name="Arguments.arguments" />
                   </elementProp>
                   <stringProp name="HTTPSampler.domain">${CANARY_SERVER_IP}</stringProp>
                   <stringProp name="HTTPSampler.port">${CANARY_PORT}</stringProp>
                   <stringProp name="HTTPSampler.protocol">http</stringProp>
                   <stringProp name="HTTPSampler.contentEncoding" />
                   <stringProp name="HTTPSampler.path">logs?type=DEBUG</stringProp>
                   <stringProp name="HTTPSampler.method">GET</stringProp>
                   <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
                   <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
                   <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
                   <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
                   <stringProp name="HTTPSampler.embedded_url_re" />
                   <stringProp name="HTTPSampler.connect_timeout" />
                   <stringProp name="HTTPSampler.response_timeout" />
                </HTTPSamplerProxy>
                <hashTree />
             </hashTree>
             <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="CANARY_INFO_THREAD" enabled="true">
                <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
                <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
                   <boolProp name="LoopController.continue_forever">false</boolProp>
                   <intProp name="LoopController.loops">-1</intProp>
                </elementProp>
                <stringProp name="ThreadGroup.num_threads">1</stringProp>
                <stringProp name="ThreadGroup.ramp_time">0</stringProp>
                <boolProp name="ThreadGroup.scheduler">true</boolProp>
                <stringProp name="ThreadGroup.duration">${RUN_DURATION}</stringProp>
                <stringProp name="ThreadGroup.delay" />
                <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
             </ThreadGroup>
             <hashTree>
                <ConstantThroughputTimer guiclass="TestBeanGUI" testclass="ConstantThroughputTimer" testname="Constant Throughput Timer" enabled="true">
                   <intProp name="calcMode">2</intProp>
                   <doubleProp>
                      <name>throughput</name>
                      <value>2000.0</value>
                      <savedValue>0.0</savedValue>
                   </doubleProp>
                </ConstantThroughputTimer>
                <hashTree />
                <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
                   <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
                      <collectionProp name="Arguments.arguments" />
                   </elementProp>
                   <stringProp name="HTTPSampler.domain">${CANARY_SERVER_IP}</stringProp>
                   <stringProp name="HTTPSampler.port">${CANARY_PORT}</stringProp>
                   <stringProp name="HTTPSampler.protocol">http</stringProp>
                   <stringProp name="HTTPSampler.contentEncoding" />
                   <stringProp name="HTTPSampler.path">dogcount</stringProp>
                   <stringProp name="HTTPSampler.method">GET</stringProp>
                   <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
                   <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
                   <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
                   <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
                   <stringProp name="HTTPSampler.embedded_url_re" />
                   <stringProp name="HTTPSampler.connect_timeout" />
                   <stringProp name="HTTPSampler.response_timeout" />
                </HTTPSamplerProxy>
                <hashTree />
             </hashTree>
             <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="CANARY_INFO_THREAD" enabled="true">
                <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
                <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
                   <boolProp name="LoopController.continue_forever">false</boolProp>
                   <intProp name="LoopController.loops">-1</intProp>
                </elementProp>
                <stringProp name="ThreadGroup.num_threads">1</stringProp>
                <stringProp name="ThreadGroup.ramp_time">0</stringProp>
                <boolProp name="ThreadGroup.scheduler">true</boolProp>
                <stringProp name="ThreadGroup.duration">${RUN_DURATION}</stringProp>
                <stringProp name="ThreadGroup.delay" />
                <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
             </ThreadGroup>
             <hashTree>
                <ConstantThroughputTimer guiclass="TestBeanGUI" testclass="ConstantThroughputTimer" testname="Constant Throughput Timer" enabled="true">
                   <intProp name="calcMode">2</intProp>
                   <doubleProp>
                      <name>throughput</name>
                      <value>2000.0</value>
                      <savedValue>0.0</savedValue>
                   </doubleProp>
                </ConstantThroughputTimer>
                <hashTree />
                <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="HTTP Request" enabled="true">
                   <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
                      <collectionProp name="Arguments.arguments" />
                   </elementProp>
                   <stringProp name="HTTPSampler.domain">${CANARY_SERVER_IP}</stringProp>
                   <stringProp name="HTTPSampler.port">${CANARY_PORT}</stringProp>
                   <stringProp name="HTTPSampler.protocol">http</stringProp>
                   <stringProp name="HTTPSampler.contentEncoding" />
                   <stringProp name="HTTPSampler.path">catcount</stringProp>
                   <stringProp name="HTTPSampler.method">GET</stringProp>
                   <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
                   <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
                   <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
                   <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
                   <stringProp name="HTTPSampler.embedded_url_re" />
                   <stringProp name="HTTPSampler.connect_timeout" />
                   <stringProp name="HTTPSampler.response_timeout" />
                </HTTPSamplerProxy>
                <hashTree />
             </hashTree>
          </hashTree>
       </hashTree>
    </jmeterTestPlan>
